"""
check.py — Project health check dashboard.

Shows at a glance: data status, config status, phase progress, next step.

Usage:
    python3 tools/check.py
"""

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))


# ── Phase definitions ────────────────────────────────

PHASES = [
    {
        "num": 1, "name": "Data Understanding",
        "dir": "01_exploration",
        "key_outputs": ["results/basic_info.csv", "results/epv_check.csv"],
        "checkpoint": "EPV >= 10, cohort exclusions, prediction time point",
    },
    {
        "num": 2, "name": "Data Splitting",
        "dir": "02_splitting",
        "key_outputs": ["results/train.csv", "results/valid.csv", "results/test.csv"],
        "checkpoint": "No patient overlap, positive rate consistent",
    },
    {
        "num": 3, "name": "Preprocessing",
        "dir": "03_preprocessing",
        "key_outputs": ["results/processed_data.npz", "results/feature_names.json"],
        "checkpoint": "fit() on train only, encoding matches semantics",
    },
    {
        "num": 4, "name": "Feature Selection",
        "dir": "04_feature_selection",
        "key_outputs": ["results/selected_data.npz", "results/selected_features.json"],
        "checkpoint": "Train-only selection, EPV >= 10, Ridge baseline compared",
    },
    {
        "num": 5, "name": "Model Training",
        "dir": "05_modeling",
        "key_outputs": ["results/best_model_info.json", "results/thresholds.json"],
        "checkpoint": "No test set tuning, >= 3 families, threshold on validation",
    },
    {
        "num": 6, "name": "Evaluation",
        "dir": "06_evaluation",
        "key_outputs": ["results/test_metrics.csv", "results/test_metrics_ci.csv"],
        "checkpoint": "Full metric panel, 95% CI, calibration ECE < 0.1",
    },
    {
        "num": 7, "name": "Interpretability",
        "dir": "07_interpretability",
        "key_outputs": [],  # varies by model
        "checkpoint": "Multi-model SHAP, cross-model comparison",
    },
    {
        "num": 8, "name": "Fairness",
        "dir": "08_fairness",
        "key_outputs": ["results/subgroup_gender.csv"],
        "checkpoint": "Subgroup analysis + CI, n < 200 flagged",
    },
    {
        "num": 9, "name": "Reporting",
        "dir": "09_reporting",
        "key_outputs": [],
        "checkpoint": "TRIPOD+AI 2024 checklist, limitations",
    },
]


def check_data():
    """Check if raw data is present."""
    raw_dir = PROJECT_ROOT / "00_database" / "raw"
    csvs = list(raw_dir.glob("*.csv"))
    return csvs


def check_config():
    """Check if config.py has been customized."""
    config_path = PROJECT_ROOT / "config.py"
    if not config_path.exists():
        return "missing", {}

    text = config_path.read_text()
    info = {}

    # Check if still using defaults
    if 'your_data.csv' in text or 'PATIENT_ID_COL = "patient_id"' in text:
        # Might be default template
        if 'Auto-generated by MLGG setup wizard' in text:
            status = "configured"
        else:
            status = "default"
    else:
        status = "configured"

    # Extract key values
    import re
    for key in ["PATIENT_ID_COL", "LABEL_COL", "TIME_COL", "OUTCOME_DESCRIPTION"]:
        m = re.search(rf'{key}\s*=\s*"([^"]*)"', text)
        if m:
            info[key] = m.group(1)

    return status, info


def check_env():
    """Check if .env is configured."""
    env_path = PROJECT_ROOT / ".env"
    if not env_path.exists():
        return False
    text = env_path.read_text()
    return "sk-" in text and "your-key" not in text


def check_phases():
    """Check which phases have completed (by checking key outputs)."""
    results = []
    for phase in PHASES:
        phase_dir = PROJECT_ROOT / phase["dir"]
        if not phase_dir.exists():
            results.append(("pending", phase))
            continue

        # Check key outputs
        has_outputs = False
        if phase["key_outputs"]:
            has_outputs = all(
                (phase_dir / out).exists()
                for out in phase["key_outputs"]
            )
        else:
            # Check for any result files
            result_dir = phase_dir / "results"
            has_outputs = result_dir.exists() and any(
                f for f in result_dir.iterdir() if not f.name.startswith(".")
            )

        results.append(("done" if has_outputs else "pending", phase))

    return results


def find_next_phase(phase_results):
    """Find the first incomplete phase."""
    for status, phase in phase_results:
        if status == "pending":
            return phase
    return None


# ── Output ─────────────────────────────────────────

def print_header(text):
    print(f"\n  {text}")
    print(f"  {'─' * (len(text) + 2)}")


def main():
    print()
    print("╔══════════════════════════════════════════╗")
    print("║       MLGG Project Health Check          ║")
    print("╚══════════════════════════════════════════╝")

    # 1. Data
    print_header("Data")
    csvs = check_data()
    if csvs:
        for csv in csvs:
            size_mb = csv.stat().st_size / 1024 / 1024
            print(f"  [OK] {csv.name} ({size_mb:.1f} MB)")
    else:
        print("  [  ] No CSV in 00_database/raw/")
        print("       Run: python3 tools/setup.py --csv <your_file.csv>")

    # 2. Config
    print_header("Config")
    config_status, config_info = check_config()
    if config_status == "configured":
        print(f"  [OK] config.py configured")
        for k, v in config_info.items():
            if v:
                print(f"       {k} = \"{v}\"")
    elif config_status == "default":
        print(f"  [  ] config.py not customized yet")
        print(f"       Run: python3 tools/setup.py")
    else:
        print(f"  [!!] config.py missing")

    # 3. Qwen
    print_header("Qwen Reviewer")
    if check_env():
        print(f"  [OK] .env configured")
    else:
        print(f"  [  ] .env not set (optional)")
        print(f"       Copy .env.example to .env and fill your API key")

    # 4. Phases
    print_header("Phase Progress")
    phase_results = check_phases()
    done_count = sum(1 for s, _ in phase_results if s == "done")

    for status, phase in phase_results:
        icon = "[OK]" if status == "done" else "[  ]"
        print(f"  {icon} Phase {phase['num']}: {phase['name']}")

    print(f"\n  Progress: {done_count}/{len(PHASES)} phases complete")

    # Progress bar
    bar_len = 30
    filled = int(bar_len * done_count / len(PHASES))
    bar = "█" * filled + "░" * (bar_len - filled)
    pct = done_count / len(PHASES) * 100
    print(f"  [{bar}] {pct:.0f}%")

    # 5. Next step
    print_header("Next Step")
    if not csvs:
        print("  Put your CSV data in 00_database/raw/ or run:")
        print("  python3 tools/setup.py --csv <your_file.csv>")
    elif config_status != "configured":
        print("  Configure your project:")
        print("  python3 tools/setup.py")
    else:
        next_phase = find_next_phase(phase_results)
        if next_phase:
            script_dir = PROJECT_ROOT / next_phase["dir"] / "scripts"
            scripts = sorted(script_dir.glob("*.py")) if script_dir.exists() else []
            if scripts:
                print(f"  Run Phase {next_phase['num']}: {next_phase['name']}")
                print(f"  python3 {next_phase['dir']}/scripts/{scripts[0].name}")
                print(f"  Checkpoint: {next_phase['checkpoint']}")
            else:
                print(f"  Phase {next_phase['num']}: {next_phase['name']} — create script in {next_phase['dir']}/scripts/")
        else:
            print("  All phases complete! Run /mlgg for final review.")

    # 6. Quick commands
    print_header("Quick Commands")
    print("  python3 tools/setup.py         # Setup wizard")
    print("  python3 tools/check.py         # This dashboard")
    print("  python3 run_all.py             # Run all phases")
    print("  python3 run_all.py --from 3    # Resume from Phase 3")
    if check_env():
        print("  python3 tools/qwen_review.py --file <script.py> --check all")
    print()


if __name__ == "__main__":
    main()
