#!/usr/bin/env python3
"""
Fail-closed fairness and equity gate for publication-grade medical prediction.

Validates that subgroup fairness metrics meet thresholds required by top-tier
journals (Nature Medicine, Lancet Digital Health, JAMA, BMJ). Checks:
- Equalized odds gap across demographic/clinical subgroups
- Disparate impact ratio (80% rule)
- Subgroup-level metric minimums
- Coverage of subgroup analysis

References:
- TRIPOD+AI (BMJ 2024): fairness assessment recommendation
- PROBAST+AI (BMJ 2025): applicability across subpopulations
- Nature Medicine / Lancet DH: subgroup equity requirements
- HEAL framework (eClinicalMedicine 2024): FPR/FNR parity
- "What Is Fair?" (Statistics in Medicine 2025): impossibility theorem
"""
from __future__ import annotations

import sys as _sys; from pathlib import Path as _Path; _CORE_DIR = str(_Path(__file__).resolve().parent.parent / "core"); _sys.path.insert(0, _CORE_DIR) if _CORE_DIR not in _sys.path else None  # noqa: E702

import argparse
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from _gate_utils import add_issue, get_gate_elapsed, load_json_from_path as load_json_object
from _gate_framework import (
    GateIssue,
    Severity,
    build_report_envelope,
    get_remediation,
    print_gate_summary,
    register_remediations,
)


register_remediations({
    "missing_evaluation_report": (
        "Provide --evaluation-report pointing to a valid evaluation_report.json "
        "generated by train_select_evaluate.py."
    ),
    "invalid_evaluation_report": (
        "Fix JSON syntax in evaluation_report.json. Use a JSON linter."
    ),
    "missing_subgroup_performance": (
        "evaluation_report.json must include 'subgroup_performance' section. "
        "Re-run training with sufficient binary/categorical features for subgroup analysis."
    ),
    "no_subgroups_analyzed": (
        "No subgroup columns were analyzed. Ensure dataset contains at least one "
        "binary or low-cardinality categorical feature for equity assessment."
    ),
    "equalized_odds_gap_exceeds_threshold": (
        "Sensitivity gap across subgroups exceeds threshold. Consider: "
        "1) Rebalancing training data across subgroups, "
        "2) Subgroup-aware threshold calibration, "
        "3) Fairness-constrained optimization."
    ),
    "disparate_impact_below_threshold": (
        "Disparate impact ratio < 0.8 (four-fifths rule). Consider: "
        "1) Investigating root cause of prediction disparity, "
        "2) Applying fairness-aware preprocessing (reweighting/resampling), "
        "3) Post-processing threshold adjustment per subgroup."
    ),
    "subgroup_metric_below_minimum": (
        "A subgroup has unacceptably low performance. Investigate: "
        "1) Sample size in that subgroup, "
        "2) Feature distribution differences, "
        "3) Whether the subgroup was adequately represented in training."
    ),
    "subgroup_sample_too_small": (
        "A subgroup has too few samples for reliable fairness assessment. "
        "Consider merging with related groups or flagging as underpowered."
    ),
    "fairness_not_finite": (
        "Non-finite fairness metric detected. Check evaluation code for "
        "division-by-zero in subgroup computations."
    ),
    "fpr_parity_exceeds_threshold": (
        "False Positive Rate gap across subgroups exceeds threshold. Consider: "
        "1) Subgroup-specific threshold calibration, "
        "2) Investigating feature distribution shifts across subgroups, "
        "3) Fairness-constrained optimization targeting FPR parity."
    ),
    "fnr_parity_exceeds_threshold": (
        "False Negative Rate gap across subgroups exceeds threshold. Consider: "
        "1) Subgroup-specific threshold calibration, "
        "2) Enriching training data for underperforming subgroups, "
        "3) Fairness-constrained optimization targeting FNR parity."
    ),
    "subgroup_sample_unstable": (
        "A subgroup has fewer than 50 samples. Fairness metrics for this "
        "subgroup may be unstable. Consider collecting more data or reporting "
        "wide confidence intervals."
    ),
    "impossibility_theorem_note": (
        "Multiple fairness criteria cannot be simultaneously satisfied "
        "(impossibility theorem, LIT-050). Document which criterion was "
        "prioritized and why."
    ),
    "ppv_parity_exceeds_threshold": (
        "Positive Predictive Value gap across subgroups exceeds threshold. "
        "Consider: 1) Investigating prevalence differences across subgroups, "
        "2) Subgroup-specific threshold calibration, "
        "3) Reporting per-subgroup PPV with confidence intervals."
    ),
    "calibration_parity_exceeds_threshold": (
        "Calibration slope differs across subgroups — model is better calibrated "
        "for some groups than others. Consider: 1) Per-subgroup recalibration, "
        "2) Investigating feature distribution shifts, "
        "3) Reporting per-subgroup calibration curves."
    ),
})


# ---------------------------------------------------------------------------
# Default thresholds
# ---------------------------------------------------------------------------
DEFAULT_THRESHOLDS: Dict[str, float] = {
    # Equalized odds: max sensitivity gap across subgroups
    "equalized_odds_gap_warn": 0.10,
    "equalized_odds_gap_fail": 0.15,
    # Disparate impact ratio (four-fifths / 80% rule)
    "disparate_impact_ratio_warn": 0.85,
    "disparate_impact_ratio_fail": 0.80,
    # Minimum PR-AUC for any subgroup
    "subgroup_pr_auc_min_warn": 0.50,
    "subgroup_pr_auc_min_fail": 0.40,
    # FPR parity: max FPR gap across subgroups (HEAL framework)
    "fpr_gap_warn": 0.10,
    "fpr_gap_fail": 0.15,
    # FNR parity: max FNR gap across subgroups (HEAL framework)
    "fnr_gap_warn": 0.10,
    "fnr_gap_fail": 0.15,
    # PPV parity: max PPV gap across subgroups (predictive parity)
    "ppv_gap_warn": 0.10,
    "ppv_gap_fail": 0.15,
    # Calibration parity: max calibration slope deviation from 1.0 across subgroups
    "calibration_slope_deviation_warn": 0.20,
    "calibration_slope_deviation_fail": 0.30,
    # Minimum subgroup size for reliable assessment
    "min_subgroup_size": 20,
    # Minimum subgroup size before fairness metrics are considered unstable
    "min_subgroup_size_stable": 50,
    # Minimum subgroup size for warning (enhanced threshold)
    "min_subgroup_size_warn": 30,
    # Minimum number of subgroup features analyzed
    "min_subgroups_analyzed": 1,
}


def _to_float(v: Any) -> Optional[float]:
    """Convert to float, reject non-finite."""
    if v is None:
        return None
    try:
        f = float(v)
        if not math.isfinite(f):
            return None
        return f
    except (TypeError, ValueError):
        return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate subgroup fairness and equity metrics."
    )
    parser.add_argument(
        "--evaluation-report",
        required=True,
        help="Path to evaluation_report.json.",
    )
    parser.add_argument(
        "--report",
        help="Optional output JSON report path.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on warnings.",
    )
    # Threshold overrides
    parser.add_argument(
        "--equalized-odds-gap-fail",
        type=float,
        default=None,
        help="Override equalized odds gap fail threshold.",
    )
    parser.add_argument(
        "--disparate-impact-ratio-fail",
        type=float,
        default=None,
        help="Override disparate impact ratio fail threshold.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    failures: List[Dict[str, Any]] = []
    warnings: List[Dict[str, Any]] = []
    info: List[Dict[str, Any]] = []

    thresholds = dict(DEFAULT_THRESHOLDS)
    if args.equalized_odds_gap_fail is not None:
        thresholds["equalized_odds_gap_fail"] = args.equalized_odds_gap_fail
    if args.disparate_impact_ratio_fail is not None:
        thresholds["disparate_impact_ratio_fail"] = args.disparate_impact_ratio_fail

    # Load evaluation report
    eval_path = Path(args.evaluation_report)
    if not eval_path.is_file():
        add_issue(
            failures,
            "missing_evaluation_report",
            f"Evaluation report not found: {eval_path}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    try:
        eval_report = load_json_object(eval_path)
    except Exception as exc:
        add_issue(
            failures,
            "invalid_evaluation_report",
            f"Cannot parse evaluation report: {exc}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    # Check for fairness_assessment.status = "not_assessed" exemption
    fairness_assessment = eval_report.get("fairness_assessment", {})
    if isinstance(fairness_assessment, dict) and fairness_assessment.get("status") == "not_assessed":
        justification = fairness_assessment.get("justification", "")
        if justification:
            # Accepted: fairness not assessed with justification.
            # Severity depends on profile (resolved from request if available).
            add_issue(
                warnings,
                "fairness_not_assessed_justified",
                f"Fairness not assessed. Justification: {justification}",
                {"justification": justification, "plan": fairness_assessment.get("plan", "")},
            )
            add_issue(
                info,
                "fairness_not_assessed_info",
                "Report this limitation in the manuscript's Limitations section.",
                {},
            )
            return _finish(args, failures, warnings, info, thresholds, eval_report)
        else:
            # Not assessed without justification — still a failure
            add_issue(
                failures,
                "fairness_not_assessed_no_justification",
                "fairness_assessment.status='not_assessed' but no justification provided. "
                "Provide a justification (e.g., 'homogeneous cohort') to use this exemption.",
                {},
            )
            return _finish(args, failures, warnings, info, thresholds, eval_report)

    # Extract subgroup performance
    subgroup_perf = eval_report.get("subgroup_performance")
    if not subgroup_perf:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "No subgroup_performance section in evaluation report. "
            "To exempt, add fairness_assessment.status='not_assessed' with justification.",
            {},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    # Validate subgroup data
    features_analyzed: List[str] = []
    all_equalized_odds_gaps: List[float] = []
    all_disparate_impact_ratios: List[float] = []
    all_subgroup_pr_aucs: List[Dict[str, Any]] = []
    all_fpr_gaps: List[float] = []
    all_fnr_gaps: List[float] = []
    all_ppv_gaps: List[float] = []
    all_cal_slope_deviations: List[float] = []
    subgroup_details: List[Dict[str, Any]] = []
    total_fairness_metrics_reported: int = 0

    if isinstance(subgroup_perf, dict):
        items = subgroup_perf.items()
    elif isinstance(subgroup_perf, list):
        items = [(entry.get("feature", f"feature_{i}"), entry) for i, entry in enumerate(subgroup_perf)]
    else:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "subgroup_performance has unexpected type.",
            {"type": type(subgroup_perf).__name__},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    for feature_name, feature_data in items:
        if not isinstance(feature_data, dict):
            continue
        features_analyzed.append(str(feature_name))

        # Extract equalized odds gap
        eo_gap = _to_float(feature_data.get("equalized_odds_gap"))
        if eo_gap is not None:
            all_equalized_odds_gaps.append(eo_gap)

            if eo_gap > thresholds["equalized_odds_gap_fail"]:
                add_issue(
                    failures,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(fail threshold: {thresholds['equalized_odds_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_fail"],
                    },
                )
            elif eo_gap > thresholds["equalized_odds_gap_warn"]:
                add_issue(
                    warnings,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(warn threshold: {thresholds['equalized_odds_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_warn"],
                    },
                )

        # Extract disparate impact ratio
        di_ratio = _to_float(feature_data.get("disparate_impact_ratio"))
        if di_ratio is not None:
            all_disparate_impact_ratios.append(di_ratio)

            if di_ratio < thresholds["disparate_impact_ratio_fail"]:
                add_issue(
                    failures,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(fail threshold: {thresholds['disparate_impact_ratio_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_fail"],
                    },
                )
            elif di_ratio < thresholds["disparate_impact_ratio_warn"]:
                add_issue(
                    warnings,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(warn threshold: {thresholds['disparate_impact_ratio_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_warn"],
                    },
                )

        # Check subgroup-level metrics
        groups = feature_data.get("groups") or feature_data.get("subgroups") or []
        if isinstance(groups, dict):
            groups = [
                {**v, "group_label": k} if isinstance(v, dict) else {"group_label": k}
                for k, v in groups.items()
            ]
        for group in groups:
            if not isinstance(group, dict):
                continue
            n = group.get("n", group.get("count", 0))
            if isinstance(n, (int, float)) and n < thresholds["min_subgroup_size"]:
                add_issue(
                    warnings,
                    "subgroup_sample_too_small",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has only {n} samples.",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_required": thresholds["min_subgroup_size"],
                    },
                )
            elif isinstance(n, (int, float)) and n < thresholds["min_subgroup_size_warn"]:
                add_issue(
                    warnings,
                    "subgroup_sample_too_small",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has only {n} samples "
                    f"(warn threshold: {int(thresholds['min_subgroup_size_warn'])}).",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_required": thresholds["min_subgroup_size_warn"],
                    },
                )
            if isinstance(n, (int, float)) and n < thresholds["min_subgroup_size_stable"]:
                add_issue(
                    warnings,
                    "subgroup_sample_unstable",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has {n} samples — fairness metrics may be unstable.",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_stable": thresholds["min_subgroup_size_stable"],
                    },
                )
            pr_auc = _to_float(group.get("pr_auc"))
            if pr_auc is not None:
                all_subgroup_pr_aucs.append({
                    "feature": feature_name,
                    "group": group.get("group_label"),
                    "pr_auc": pr_auc,
                })
                if pr_auc < thresholds["subgroup_pr_auc_min_fail"]:
                    add_issue(
                        failures,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(fail: {thresholds['subgroup_pr_auc_min_fail']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )
                elif pr_auc < thresholds["subgroup_pr_auc_min_warn"]:
                    add_issue(
                        warnings,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(warn: {thresholds['subgroup_pr_auc_min_warn']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )

        # ── FPR parity check (HEAL framework, eClinicalMedicine 2024) ────
        fpr_gap = None
        group_fprs = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            fpr = _to_float(group.get("fpr", group.get("false_positive_rate")))
            if fpr is not None:
                group_fprs.append(fpr)
        if len(group_fprs) >= 2:
            fpr_gap = max(group_fprs) - min(group_fprs)
            all_fpr_gaps.append(fpr_gap)
            if fpr_gap > thresholds["fpr_gap_fail"]:
                add_issue(
                    failures,
                    "fpr_parity_exceeds_threshold",
                    f"FPR gap for '{feature_name}' is {fpr_gap:.3f} "
                    f"(fail threshold: {thresholds['fpr_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fpr_gap,
                        "threshold": thresholds["fpr_gap_fail"],
                    },
                )
            elif fpr_gap > thresholds["fpr_gap_warn"]:
                add_issue(
                    warnings,
                    "fpr_parity_exceeds_threshold",
                    f"FPR gap for '{feature_name}' is {fpr_gap:.3f} "
                    f"(warn threshold: {thresholds['fpr_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fpr_gap,
                        "threshold": thresholds["fpr_gap_warn"],
                    },
                )

        # ── FNR parity check (HEAL framework, eClinicalMedicine 2024) ────
        fnr_gap = None
        group_fnrs = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            fnr = _to_float(group.get("fnr", group.get("false_negative_rate")))
            if fnr is not None:
                group_fnrs.append(fnr)
        if len(group_fnrs) >= 2:
            fnr_gap = max(group_fnrs) - min(group_fnrs)
            all_fnr_gaps.append(fnr_gap)
            if fnr_gap > thresholds["fnr_gap_fail"]:
                add_issue(
                    failures,
                    "fnr_parity_exceeds_threshold",
                    f"FNR gap for '{feature_name}' is {fnr_gap:.3f} "
                    f"(fail threshold: {thresholds['fnr_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fnr_gap,
                        "threshold": thresholds["fnr_gap_fail"],
                    },
                )
            elif fnr_gap > thresholds["fnr_gap_warn"]:
                add_issue(
                    warnings,
                    "fnr_parity_exceeds_threshold",
                    f"FNR gap for '{feature_name}' is {fnr_gap:.3f} "
                    f"(warn threshold: {thresholds['fnr_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fnr_gap,
                        "threshold": thresholds["fnr_gap_warn"],
                    },
                )

        # ── PPV parity check (predictive parity) ──────────────────────
        ppv_gap = None
        group_ppvs: List[float] = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            ppv = _to_float(group.get("ppv", group.get("precision")))
            if ppv is not None:
                group_ppvs.append(ppv)
        if len(group_ppvs) >= 2:
            ppv_gap = max(group_ppvs) - min(group_ppvs)
            all_ppv_gaps.append(ppv_gap)
            if ppv_gap > thresholds["ppv_gap_fail"]:
                add_issue(
                    failures,
                    "ppv_parity_exceeds_threshold",
                    f"PPV gap for '{feature_name}' is {ppv_gap:.3f} "
                    f"(fail threshold: {thresholds['ppv_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": ppv_gap,
                        "threshold": thresholds["ppv_gap_fail"],
                    },
                )
            elif ppv_gap > thresholds["ppv_gap_warn"]:
                add_issue(
                    warnings,
                    "ppv_parity_exceeds_threshold",
                    f"PPV gap for '{feature_name}' is {ppv_gap:.3f} "
                    f"(warn threshold: {thresholds['ppv_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": ppv_gap,
                        "threshold": thresholds["ppv_gap_warn"],
                    },
                )

        # ── Calibration parity check ──────────────────────────────
        cal_slope_deviation = None
        group_cal_slopes: List[float] = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            cal_slope = _to_float(group.get("calibration_slope"))
            if cal_slope is not None:
                group_cal_slopes.append(cal_slope)
        if len(group_cal_slopes) >= 2:
            max_dev = max(abs(s - 1.0) for s in group_cal_slopes)
            cal_slope_deviation = max_dev
            all_cal_slope_deviations.append(max_dev)
            if max_dev > thresholds["calibration_slope_deviation_fail"]:
                add_issue(
                    failures,
                    "calibration_parity_exceeds_threshold",
                    f"Calibration slope deviation for '{feature_name}' is {max_dev:.3f} "
                    f"(fail threshold: {thresholds['calibration_slope_deviation_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "max_deviation": max_dev,
                        "slopes": group_cal_slopes,
                        "threshold": thresholds["calibration_slope_deviation_fail"],
                    },
                )
            elif max_dev > thresholds["calibration_slope_deviation_warn"]:
                add_issue(
                    warnings,
                    "calibration_parity_exceeds_threshold",
                    f"Calibration slope deviation for '{feature_name}' is {max_dev:.3f} "
                    f"(warn threshold: {thresholds['calibration_slope_deviation_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "max_deviation": max_dev,
                        "slopes": group_cal_slopes,
                        "threshold": thresholds["calibration_slope_deviation_warn"],
                    },
                )

        # Count distinct fairness metrics reported for this feature
        _feature_metrics = 0
        if eo_gap is not None:
            _feature_metrics += 1
        if di_ratio is not None:
            _feature_metrics += 1
        if len(group_fprs) >= 2:
            _feature_metrics += 1
        if len(group_fnrs) >= 2:
            _feature_metrics += 1
        if len(group_ppvs) >= 2:
            _feature_metrics += 1
        if len(group_cal_slopes) >= 2:
            _feature_metrics += 1
        total_fairness_metrics_reported += _feature_metrics

        subgroup_details.append({
            "feature": feature_name,
            "equalized_odds_gap": eo_gap,
            "disparate_impact_ratio": di_ratio,
            "fpr_gap": fpr_gap,
            "fnr_gap": fnr_gap,
            "ppv_gap": ppv_gap,
            "calibration_slope_deviation": cal_slope_deviation,
            "n_groups": len(groups),
        })

    # ── Multiplicity warning ─────────────────────────────────────────
    # When many subgroup × metric comparisons are made, the chance of
    # a false alarm rises.  Report total comparisons and warn.
    n_comparisons = len(features_analyzed) * 7  # 7 metric types per feature
    if n_comparisons > 10:
        add_issue(
            warnings,
            "multiple_comparisons_unadjusted",
            f"{n_comparisons} fairness comparisons made across "
            f"{len(features_analyzed)} features without multiplicity correction. "
            "Some flagged disparities may be due to chance. "
            "Consider Bonferroni or FDR-BH adjustment before interpreting.",
            {
                "n_features": len(features_analyzed),
                "metrics_per_feature": 7,
                "n_comparisons": n_comparisons,
                "bonferroni_adjusted_alpha": round(0.05 / n_comparisons, 4) if n_comparisons > 0 else 0.05,
            },
        )

    # ── Impossibility theorem acknowledgment ("What Is Fair?", Stat Med 2025) ──
    if total_fairness_metrics_reported >= 3:
        add_issue(
            info,
            "impossibility_theorem_note",
            "Multiple fairness criteria cannot be simultaneously satisfied "
            "(impossibility theorem, LIT-050). Document which criterion was "
            "prioritized and why.",
            {"n_metrics_reported": total_fairness_metrics_reported},
        )

    # Check minimum subgroup coverage
    if len(features_analyzed) < thresholds["min_subgroups_analyzed"]:
        add_issue(
            failures,
            "no_subgroups_analyzed",
            f"Only {len(features_analyzed)} subgroup feature(s) analyzed "
            f"(minimum: {int(thresholds['min_subgroups_analyzed'])}).",
            {"count": len(features_analyzed)},
        )

    # Summary
    summary = {
        "features_analyzed": features_analyzed,
        "n_features_analyzed": len(features_analyzed),
        "equalized_odds_gaps": all_equalized_odds_gaps,
        "max_equalized_odds_gap": (
            max(all_equalized_odds_gaps) if all_equalized_odds_gaps else None
        ),
        "disparate_impact_ratios": all_disparate_impact_ratios,
        "min_disparate_impact_ratio": (
            min(all_disparate_impact_ratios)
            if all_disparate_impact_ratios
            else None
        ),
        "fpr_gaps": all_fpr_gaps,
        "max_fpr_gap": max(all_fpr_gaps) if all_fpr_gaps else None,
        "fnr_gaps": all_fnr_gaps,
        "max_fnr_gap": max(all_fnr_gaps) if all_fnr_gaps else None,
        "ppv_gaps": all_ppv_gaps,
        "max_ppv_gap": max(all_ppv_gaps) if all_ppv_gaps else None,
        "calibration_slope_deviations": all_cal_slope_deviations,
        "max_calibration_slope_deviation": (
            max(all_cal_slope_deviations) if all_cal_slope_deviations else None
        ),
        "total_fairness_metrics_reported": total_fairness_metrics_reported,
        "subgroup_details": subgroup_details,
        "thresholds": thresholds,
    }

    return _finish(args, failures, warnings, info, thresholds, eval_report, summary)


def _finish(
    args: argparse.Namespace,
    failures: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    info: List[Dict[str, Any]],
    thresholds: Dict[str, float],
    eval_report: Optional[Dict[str, Any]],
    summary: Optional[Dict[str, Any]] = None,
) -> int:
    should_fail = bool(failures) or (args.strict and bool(warnings))
    status = "fail" if should_fail else "pass"

    fi = [GateIssue.from_legacy(f, Severity.ERROR) for f in failures]
    wi = [GateIssue.from_legacy(w, Severity.WARNING) for w in warnings]
    for issue in fi + wi:
        if not issue.remediation:
            issue.remediation = get_remediation(issue.code)

    report = build_report_envelope(
        gate_name="fairness_equity_gate",
        status=status,
        strict_mode=bool(args.strict),
        failures=fi,
        warnings=wi,
        extra={
            "thresholds": thresholds,
            "summary": summary or {},
            "info": info,
        },
    )

    if args.report:
        out = Path(args.report)
        out.parent.mkdir(parents=True, exist_ok=True)
        import json
        out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    print_gate_summary("Fairness & Equity Gate", status, fi, wi, bool(args.strict), get_gate_elapsed())
    return 2 if should_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
