#!/usr/bin/env python3
"""
Fail-closed fairness and equity gate for publication-grade medical prediction.

Validates that subgroup fairness metrics meet thresholds required by top-tier
journals (Nature Medicine, Lancet Digital Health, JAMA, BMJ). Checks:
- Equalized odds gap across demographic/clinical subgroups
- Disparate impact ratio (80% rule)
- Subgroup-level metric minimums
- Coverage of subgroup analysis

References:
- Collins GS et al. BMJ 2024;385:e078378 (TRIPOD+AI): fairness assessment recommendation
- Moons KGM et al. BMJ 2025;388:e082505 (PROBAST+AI): applicability across subpopulations
- Obermeyer Z et al. Science 2019;366:447-453: racial bias in health algorithms
"""
from __future__ import annotations

import sys as _sys; from pathlib import Path as _Path; _CORE_DIR = str(_Path(__file__).resolve().parent.parent / "core"); _sys.path.insert(0, _CORE_DIR) if _CORE_DIR not in _sys.path else None  # noqa: E702

import argparse
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from _gate_utils import finite_float, add_issue, get_gate_elapsed, load_json_from_path as load_json_object
from _gate_framework import (
    GateIssue,
    Severity,
    build_report_envelope,
    get_remediation,
    print_gate_summary,
    register_remediations,
)


register_remediations({
    "missing_evaluation_report": (
        "Provide --evaluation-report pointing to a valid evaluation_report.json "
        "generated by train_select_evaluate.py."
    ),
    "invalid_evaluation_report": (
        "Fix JSON syntax in evaluation_report.json. Use a JSON linter."
    ),
    "missing_subgroup_performance": (
        "evaluation_report.json must include 'subgroup_performance' section. "
        "Re-run training with sufficient binary/categorical features for subgroup analysis."
    ),
    "no_subgroups_analyzed": (
        "No subgroup columns were analyzed. Ensure dataset contains at least one "
        "binary or low-cardinality categorical feature for equity assessment."
    ),
    "equalized_odds_gap_exceeds_threshold": (
        "Sensitivity gap across subgroups exceeds threshold. Consider: "
        "1) Rebalancing training data across subgroups, "
        "2) Subgroup-aware threshold calibration, "
        "3) Fairness-constrained optimization."
    ),
    "disparate_impact_below_threshold": (
        "Disparate impact ratio < 0.8 (four-fifths rule). Consider: "
        "1) Investigating root cause of prediction disparity, "
        "2) Applying fairness-aware preprocessing (reweighting/resampling), "
        "3) Post-processing threshold adjustment per subgroup."
    ),
    "subgroup_metric_below_minimum": (
        "A subgroup has unacceptably low performance. Investigate: "
        "1) Sample size in that subgroup, "
        "2) Feature distribution differences, "
        "3) Whether the subgroup was adequately represented in training."
    ),
    "subgroup_sample_too_small": (
        "A subgroup has too few samples for reliable fairness assessment. "
        "Consider merging with related groups or flagging as underpowered."
    ),
    "fairness_not_finite": (
        "Non-finite fairness metric detected. Check evaluation code for "
        "division-by-zero in subgroup computations."
    ),
    "fpr_parity_exceeds_threshold": (
        "False Positive Rate gap across subgroups exceeds threshold. Consider: "
        "1) Subgroup-specific threshold calibration, "
        "2) Investigating feature distribution shifts across subgroups, "
        "3) Fairness-constrained optimization targeting FPR parity."
    ),
    "fnr_parity_exceeds_threshold": (
        "False Negative Rate gap across subgroups exceeds threshold. Consider: "
        "1) Subgroup-specific threshold calibration, "
        "2) Enriching training data for underperforming subgroups, "
        "3) Fairness-constrained optimization targeting FNR parity."
    ),
    "subgroup_sample_unstable": (
        "A subgroup has fewer than 50 samples. Fairness metrics for this "
        "subgroup may be unstable. Consider collecting more data or reporting "
        "wide confidence intervals."
    ),
    "impossibility_theorem_note": (
        "Multiple fairness criteria cannot be simultaneously satisfied "
        "(impossibility theorem, LIT-050). Document which criterion was "
        "prioritized and why."
    ),
    "ppv_parity_exceeds_threshold": (
        "Positive Predictive Value gap across subgroups exceeds threshold. "
        "Consider: 1) Investigating prevalence differences across subgroups, "
        "2) Subgroup-specific threshold calibration, "
        "3) Reporting per-subgroup PPV with confidence intervals."
    ),
    "calibration_parity_exceeds_threshold": (
        "Calibration slope differs across subgroups — model is better calibrated "
        "for some groups than others. Consider: 1) Per-subgroup recalibration, "
        "2) Investigating feature distribution shifts, "
        "3) Reporting per-subgroup calibration curves."
    ),
    "fairness_subgroup_dca_negative": (
        "A subgroup has negative net benefit at a clinically-relevant threshold "
        "in subgroup-stratified Decision Curve Analysis (DCA). This means the "
        "model would do net harm if used to make treatment decisions for that "
        "subgroup. Consider: 1) Per-subgroup threshold calibration, "
        "2) Restricting clinical deployment to subgroups with positive net "
        "benefit, 3) Retraining with better representation of the harmed "
        "subgroup. Ref: Vickers AJ, Elkin EB. Med Decis Making 2006;26:565-574."
    ),
    "subgroup_dca_input_missing": (
        "--subgroup-dca (or --strict) was requested but a prediction trace with "
        "a subgroup column was not provided. Pass --prediction-trace <path.csv> "
        "and --subgroup-dca-column <colname> so the gate can compute "
        "subgroup-stratified DCA. The trace must contain y_true, y_score, and "
        "the named subgroup column."
    ),
    "subgroup_dca_input_unreadable": (
        "Failed to read or parse the prediction trace passed via "
        "--prediction-trace. Confirm the file exists, is CSV-formatted, and "
        "contains y_true, y_score, and the --subgroup-dca-column column."
    ),
    "subgroup_dca_skipped_insufficient_data": (
        "Subgroup DCA was requested but could not be computed (e.g. all "
        "subgroups too small, or no group has >= 20 samples). Provide a "
        "larger evaluation sample or a coarser subgroup partition."
    ),
})


# ---------------------------------------------------------------------------
# Default thresholds
# ---------------------------------------------------------------------------
DEFAULT_THRESHOLDS: Dict[str, float] = {
    # Equalized odds: max sensitivity gap across subgroups
    "equalized_odds_gap_warn": 0.10,
    "equalized_odds_gap_fail": 0.15,
    # Disparate impact ratio (four-fifths / 80% rule)
    "disparate_impact_ratio_warn": 0.85,
    "disparate_impact_ratio_fail": 0.80,
    # Minimum PR-AUC for any subgroup
    "subgroup_pr_auc_min_warn": 0.50,
    "subgroup_pr_auc_min_fail": 0.40,
    # FPR parity: max FPR gap across subgroups (HEAL framework)
    "fpr_gap_warn": 0.10,
    "fpr_gap_fail": 0.15,
    # FNR parity: max FNR gap across subgroups (HEAL framework)
    "fnr_gap_warn": 0.10,
    "fnr_gap_fail": 0.15,
    # PPV parity: max PPV gap across subgroups (predictive parity)
    "ppv_gap_warn": 0.10,
    "ppv_gap_fail": 0.15,
    # Calibration parity: max calibration slope deviation from 1.0 across subgroups
    "calibration_slope_deviation_warn": 0.20,
    "calibration_slope_deviation_fail": 0.30,
    # Minimum subgroup size for reliable assessment
    "min_subgroup_size": 20,
    # Minimum subgroup size before fairness metrics are considered unstable
    "min_subgroup_size_stable": 50,
    # Minimum subgroup size for warning (enhanced threshold)
    "min_subgroup_size_warn": 30,
    # Minimum number of subgroup features analyzed
    "min_subgroups_analyzed": 1,
    # Subgroup-DCA: clinically-relevant threshold range to assess net benefit
    # Default 0.05–0.20 covers the band where most binary-outcome clinical
    # decisions are made (Vickers AJ, BMJ 2016;352:i6). A subgroup whose best
    # net benefit across this band is < 0 indicates net harm if the model is
    # used to drive treatment decisions for that subgroup.
    "subgroup_dca_threshold_min": 0.05,
    "subgroup_dca_threshold_max": 0.20,
    "subgroup_dca_net_benefit_fail": 0.0,
}


def _to_float(v: Any) -> Optional[float]:
    """Convert to float, reject non-finite."""
    if v is None:
        return None
    try:
        f = float(v)
        if not math.isfinite(f):
            return None
        return f
    except (TypeError, ValueError):
        return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate subgroup fairness and equity metrics."
    )
    parser.add_argument(
        "--evaluation-report",
        required=True,
        help="Path to evaluation_report.json.",
    )
    parser.add_argument(
        "--report",
        help="Optional output JSON report path.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on warnings.",
    )
    # Threshold overrides
    parser.add_argument(
        "--equalized-odds-gap-fail",
        type=finite_float,
        default=None,
        help="Override equalized odds gap fail threshold.",
    )
    parser.add_argument(
        "--disparate-impact-ratio-fail",
        type=finite_float,
        default=None,
        help="Override disparate impact ratio fail threshold.",
    )
    # ── Subgroup DCA (opt-in; auto-enabled under --strict) ────────────────
    parser.add_argument(
        "--subgroup-dca",
        action="store_true",
        help="Opt-in: run subgroup-stratified Decision Curve Analysis. "
             "Requires --prediction-trace and --subgroup-dca-column. "
             "Auto-enabled when --strict is set (publication-grade).",
    )
    parser.add_argument(
        "--prediction-trace",
        default=None,
        help="Path to a CSV trace with columns y_true, y_score, and the "
             "--subgroup-dca-column. Required when --subgroup-dca is active.",
    )
    parser.add_argument(
        "--subgroup-dca-column",
        default=None,
        help="Column name in the prediction trace that holds subgroup labels.",
    )
    parser.add_argument(
        "--subgroup-dca-threshold-min",
        type=finite_float,
        default=None,
        help="Lower bound of clinically-relevant probability threshold range "
             "for subgroup-DCA net-benefit assessment (default 0.05).",
    )
    parser.add_argument(
        "--subgroup-dca-threshold-max",
        type=finite_float,
        default=None,
        help="Upper bound of clinically-relevant probability threshold range "
             "for subgroup-DCA net-benefit assessment (default 0.20).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    failures: List[Dict[str, Any]] = []
    warnings: List[Dict[str, Any]] = []
    info: List[Dict[str, Any]] = []

    thresholds = dict(DEFAULT_THRESHOLDS)
    if args.equalized_odds_gap_fail is not None:
        thresholds["equalized_odds_gap_fail"] = args.equalized_odds_gap_fail
    if args.disparate_impact_ratio_fail is not None:
        thresholds["disparate_impact_ratio_fail"] = args.disparate_impact_ratio_fail

    # Load evaluation report
    eval_path = Path(args.evaluation_report)
    if not eval_path.is_file():
        add_issue(
            failures,
            "missing_evaluation_report",
            f"Evaluation report not found: {eval_path}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    try:
        eval_report = load_json_object(eval_path)
    except Exception as exc:
        add_issue(
            failures,
            "invalid_evaluation_report",
            f"Cannot parse evaluation report: {exc}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    # Check for fairness_assessment.status = "not_assessed" exemption
    fairness_assessment = eval_report.get("fairness_assessment", {})
    if isinstance(fairness_assessment, dict) and fairness_assessment.get("status") == "not_assessed":
        justification = fairness_assessment.get("justification", "")
        if justification:
            # Accepted: fairness not assessed with justification.
            # Severity depends on profile (resolved from request if available).
            add_issue(
                warnings,
                "fairness_not_assessed_justified",
                f"Fairness not assessed. Justification: {justification}",
                {"justification": justification, "plan": fairness_assessment.get("plan", "")},
            )
            add_issue(
                info,
                "fairness_not_assessed_info",
                "Report this limitation in the manuscript's Limitations section.",
                {},
            )
            return _finish(args, failures, warnings, info, thresholds, eval_report)
        else:
            # Not assessed without justification — still a failure
            add_issue(
                failures,
                "fairness_not_assessed_no_justification",
                "fairness_assessment.status='not_assessed' but no justification provided. "
                "Provide a justification (e.g., 'homogeneous cohort') to use this exemption.",
                {},
            )
            return _finish(args, failures, warnings, info, thresholds, eval_report)

    # Extract subgroup performance
    subgroup_perf = eval_report.get("subgroup_performance")
    if not subgroup_perf:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "No subgroup_performance section in evaluation report. "
            "To exempt, add fairness_assessment.status='not_assessed' with justification.",
            {},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    # Validate subgroup data
    features_analyzed: List[str] = []
    all_equalized_odds_gaps: List[float] = []
    all_disparate_impact_ratios: List[float] = []
    all_subgroup_pr_aucs: List[Dict[str, Any]] = []
    all_fpr_gaps: List[float] = []
    all_fnr_gaps: List[float] = []
    all_ppv_gaps: List[float] = []
    all_cal_slope_deviations: List[float] = []
    subgroup_details: List[Dict[str, Any]] = []
    total_fairness_metrics_reported: int = 0

    # train_select_evaluate emits two possible shapes:
    #   (1) flat: {feat_a: {...}, feat_b: {...}}
    #   (2) nested: {disparate_impact_ratio: 0.77, features_analyzed: [...],
    #               subgroups: {feat_a: {...}, feat_b: {...}}}
    # Detect shape (2) and drill into .subgroups; otherwise iterate flat.
    if isinstance(subgroup_perf, dict):
        nested = subgroup_perf.get("subgroups")
        if isinstance(nested, dict) and nested:
            items = nested.items()
            # Propagate precomputed top-level disparate-impact ratio to the
            # per-feature accumulator so the gate can evaluate it even when
            # the nested feature blocks don't carry their own copy.
            top_di = _to_float(subgroup_perf.get("disparate_impact_ratio"))
            if top_di is not None and top_di > 0:
                all_disparate_impact_ratios.append(top_di)
                if top_di < thresholds["disparate_impact_ratio_fail"]:
                    add_issue(
                        failures, "disparate_impact_below_threshold",
                        f"Overall disparate impact ratio {top_di:.3f} < fail threshold "
                        f"{thresholds['disparate_impact_ratio_fail']}.",
                        {"ratio": top_di, "threshold": thresholds["disparate_impact_ratio_fail"]},
                    )
                elif top_di < thresholds["disparate_impact_ratio_warn"]:
                    add_issue(
                        warnings, "disparate_impact_below_threshold",
                        f"Overall disparate impact ratio {top_di:.3f} < warn threshold "
                        f"{thresholds['disparate_impact_ratio_warn']}.",
                        {"ratio": top_di, "threshold": thresholds["disparate_impact_ratio_warn"]},
                    )
        else:
            items = subgroup_perf.items()
    elif isinstance(subgroup_perf, list):
        items = [(entry.get("feature", f"feature_{i}"), entry) for i, entry in enumerate(subgroup_perf)]
    else:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "subgroup_performance has unexpected type.",
            {"type": type(subgroup_perf).__name__},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    for feature_name, feature_data in items:
        if not isinstance(feature_data, dict):
            continue
        features_analyzed.append(str(feature_name))

        # Extract equalized odds gap
        eo_gap = _to_float(feature_data.get("equalized_odds_gap"))
        if eo_gap is not None:
            all_equalized_odds_gaps.append(eo_gap)

            if eo_gap > thresholds["equalized_odds_gap_fail"]:
                add_issue(
                    failures,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(fail threshold: {thresholds['equalized_odds_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_fail"],
                    },
                )
            elif eo_gap > thresholds["equalized_odds_gap_warn"]:
                add_issue(
                    warnings,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(warn threshold: {thresholds['equalized_odds_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_warn"],
                    },
                )

        # Extract disparate impact ratio
        di_ratio = _to_float(feature_data.get("disparate_impact_ratio"))
        if di_ratio is not None:
            all_disparate_impact_ratios.append(di_ratio)

            if di_ratio < thresholds["disparate_impact_ratio_fail"]:
                add_issue(
                    failures,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(fail threshold: {thresholds['disparate_impact_ratio_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_fail"],
                    },
                )
            elif di_ratio < thresholds["disparate_impact_ratio_warn"]:
                add_issue(
                    warnings,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(warn threshold: {thresholds['disparate_impact_ratio_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_warn"],
                    },
                )

        # Check subgroup-level metrics
        groups = feature_data.get("groups") or feature_data.get("subgroups") or []
        if isinstance(groups, dict):
            groups = [
                {**v, "group_label": k} if isinstance(v, dict) else {"group_label": k}
                for k, v in groups.items()
            ]
        for group in groups:
            if not isinstance(group, dict):
                continue
            n = group.get("n", group.get("count", 0))
            if isinstance(n, (int, float)) and n < thresholds["min_subgroup_size"]:
                add_issue(
                    warnings,
                    "subgroup_sample_too_small",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has only {n} samples.",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_required": thresholds["min_subgroup_size"],
                    },
                )
            elif isinstance(n, (int, float)) and n < thresholds["min_subgroup_size_warn"]:
                add_issue(
                    warnings,
                    "subgroup_sample_too_small",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has only {n} samples "
                    f"(warn threshold: {int(thresholds['min_subgroup_size_warn'])}).",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_required": thresholds["min_subgroup_size_warn"],
                    },
                )
            elif isinstance(n, (int, float)) and n < thresholds["min_subgroup_size_stable"]:
                # Only warn about instability if not already flagged as too_small
                add_issue(
                    warnings,
                    "subgroup_sample_unstable",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has {n} samples — fairness metrics may be unstable.",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_stable": thresholds["min_subgroup_size_stable"],
                    },
                )
            pr_auc = _to_float(group.get("pr_auc"))
            if pr_auc is not None:
                all_subgroup_pr_aucs.append({
                    "feature": feature_name,
                    "group": group.get("group_label"),
                    "pr_auc": pr_auc,
                })
                if pr_auc < thresholds["subgroup_pr_auc_min_fail"]:
                    add_issue(
                        failures,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(fail: {thresholds['subgroup_pr_auc_min_fail']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )
                elif pr_auc < thresholds["subgroup_pr_auc_min_warn"]:
                    add_issue(
                        warnings,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(warn: {thresholds['subgroup_pr_auc_min_warn']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )

        # ── FPR parity check (HEAL framework, eClinicalMedicine 2024) ────
        fpr_gap = None
        group_fprs = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            fpr = _to_float(group.get("fpr", group.get("false_positive_rate")))
            if fpr is not None:
                group_fprs.append(fpr)
        if len(group_fprs) >= 2:
            fpr_gap = max(group_fprs) - min(group_fprs)
            all_fpr_gaps.append(fpr_gap)
            if fpr_gap > thresholds["fpr_gap_fail"]:
                add_issue(
                    failures,
                    "fpr_parity_exceeds_threshold",
                    f"FPR gap for '{feature_name}' is {fpr_gap:.3f} "
                    f"(fail threshold: {thresholds['fpr_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fpr_gap,
                        "threshold": thresholds["fpr_gap_fail"],
                    },
                )
            elif fpr_gap > thresholds["fpr_gap_warn"]:
                add_issue(
                    warnings,
                    "fpr_parity_exceeds_threshold",
                    f"FPR gap for '{feature_name}' is {fpr_gap:.3f} "
                    f"(warn threshold: {thresholds['fpr_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fpr_gap,
                        "threshold": thresholds["fpr_gap_warn"],
                    },
                )

        # ── FNR parity check (HEAL framework, eClinicalMedicine 2024) ────
        fnr_gap = None
        group_fnrs = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            fnr = _to_float(group.get("fnr", group.get("false_negative_rate")))
            if fnr is not None:
                group_fnrs.append(fnr)
        if len(group_fnrs) >= 2:
            fnr_gap = max(group_fnrs) - min(group_fnrs)
            all_fnr_gaps.append(fnr_gap)
            if fnr_gap > thresholds["fnr_gap_fail"]:
                add_issue(
                    failures,
                    "fnr_parity_exceeds_threshold",
                    f"FNR gap for '{feature_name}' is {fnr_gap:.3f} "
                    f"(fail threshold: {thresholds['fnr_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fnr_gap,
                        "threshold": thresholds["fnr_gap_fail"],
                    },
                )
            elif fnr_gap > thresholds["fnr_gap_warn"]:
                add_issue(
                    warnings,
                    "fnr_parity_exceeds_threshold",
                    f"FNR gap for '{feature_name}' is {fnr_gap:.3f} "
                    f"(warn threshold: {thresholds['fnr_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": fnr_gap,
                        "threshold": thresholds["fnr_gap_warn"],
                    },
                )

        # ── PPV parity check (predictive parity) ──────────────────────
        ppv_gap = None
        group_ppvs: List[float] = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            ppv = _to_float(group.get("ppv", group.get("precision")))
            if ppv is not None:
                group_ppvs.append(ppv)
        if len(group_ppvs) >= 2:
            ppv_gap = max(group_ppvs) - min(group_ppvs)
            all_ppv_gaps.append(ppv_gap)
            if ppv_gap > thresholds["ppv_gap_fail"]:
                add_issue(
                    failures,
                    "ppv_parity_exceeds_threshold",
                    f"PPV gap for '{feature_name}' is {ppv_gap:.3f} "
                    f"(fail threshold: {thresholds['ppv_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": ppv_gap,
                        "threshold": thresholds["ppv_gap_fail"],
                    },
                )
            elif ppv_gap > thresholds["ppv_gap_warn"]:
                add_issue(
                    warnings,
                    "ppv_parity_exceeds_threshold",
                    f"PPV gap for '{feature_name}' is {ppv_gap:.3f} "
                    f"(warn threshold: {thresholds['ppv_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": ppv_gap,
                        "threshold": thresholds["ppv_gap_warn"],
                    },
                )

        # ── Calibration parity check ──────────────────────────────
        cal_slope_deviation = None
        group_cal_slopes: List[float] = []
        for group in groups:
            if not isinstance(group, dict):
                continue
            cal_slope = _to_float(group.get("calibration_slope"))
            if cal_slope is not None:
                group_cal_slopes.append(cal_slope)
        if len(group_cal_slopes) >= 2:
            max_dev = max(abs(s - 1.0) for s in group_cal_slopes)
            cal_slope_deviation = max_dev
            all_cal_slope_deviations.append(max_dev)
            if max_dev > thresholds["calibration_slope_deviation_fail"]:
                add_issue(
                    failures,
                    "calibration_parity_exceeds_threshold",
                    f"Calibration slope deviation for '{feature_name}' is {max_dev:.3f} "
                    f"(fail threshold: {thresholds['calibration_slope_deviation_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "max_deviation": max_dev,
                        "slopes": group_cal_slopes,
                        "threshold": thresholds["calibration_slope_deviation_fail"],
                    },
                )
            elif max_dev > thresholds["calibration_slope_deviation_warn"]:
                add_issue(
                    warnings,
                    "calibration_parity_exceeds_threshold",
                    f"Calibration slope deviation for '{feature_name}' is {max_dev:.3f} "
                    f"(warn threshold: {thresholds['calibration_slope_deviation_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "max_deviation": max_dev,
                        "slopes": group_cal_slopes,
                        "threshold": thresholds["calibration_slope_deviation_warn"],
                    },
                )

        # Count distinct fairness metrics reported for this feature
        _feature_metrics = 0
        if eo_gap is not None:
            _feature_metrics += 1
        if di_ratio is not None:
            _feature_metrics += 1
        if len(group_fprs) >= 2:
            _feature_metrics += 1
        if len(group_fnrs) >= 2:
            _feature_metrics += 1
        if len(group_ppvs) >= 2:
            _feature_metrics += 1
        if len(group_cal_slopes) >= 2:
            _feature_metrics += 1
        total_fairness_metrics_reported += _feature_metrics

        subgroup_details.append({
            "feature": feature_name,
            "equalized_odds_gap": eo_gap,
            "disparate_impact_ratio": di_ratio,
            "fpr_gap": fpr_gap,
            "fnr_gap": fnr_gap,
            "ppv_gap": ppv_gap,
            "calibration_slope_deviation": cal_slope_deviation,
            "n_groups": len(groups),
        })

    # ── Multiplicity warning ─────────────────────────────────────────
    # When many subgroup × metric comparisons are made, the chance of
    # a false alarm rises.  Report total comparisons and warn.
    n_comparisons = len(features_analyzed) * 7  # 7 metric types per feature
    if n_comparisons > 10:
        add_issue(
            warnings,
            "multiple_comparisons_unadjusted",
            f"{n_comparisons} fairness comparisons made across "
            f"{len(features_analyzed)} features without multiplicity correction. "
            "Some flagged disparities may be due to chance. "
            "Consider Bonferroni or FDR-BH adjustment before interpreting.",
            {
                "n_features": len(features_analyzed),
                "metrics_per_feature": 7,
                "n_comparisons": n_comparisons,
                "bonferroni_adjusted_alpha": round(0.05 / n_comparisons, 4) if n_comparisons > 0 else 0.05,
            },
        )

    # ── Impossibility theorem acknowledgment ("What Is Fair?", Stat Med 2025) ──
    if total_fairness_metrics_reported >= 3:
        add_issue(
            info,
            "impossibility_theorem_note",
            "Multiple fairness criteria cannot be simultaneously satisfied "
            "(impossibility theorem, LIT-050). Document which criterion was "
            "prioritized and why.",
            {"n_metrics_reported": total_fairness_metrics_reported},
        )

    # Check minimum subgroup coverage
    if len(features_analyzed) < thresholds["min_subgroups_analyzed"]:
        add_issue(
            failures,
            "no_subgroups_analyzed",
            f"Only {len(features_analyzed)} subgroup feature(s) analyzed "
            f"(minimum: {int(thresholds['min_subgroups_analyzed'])}).",
            {"count": len(features_analyzed)},
        )

    # ── Optional subgroup-DCA check (opt-in or strict) ─────────────────────
    # Default OFF to avoid breaking existing CI baselines; auto-enabled under
    # --strict because publication-grade artefacts are expected to include
    # decision-curve evidence per subgroup (Vickers & Elkin 2006).
    subgroup_dca_summary: Optional[Dict[str, Any]] = None
    if args.subgroup_dca or args.strict:
        subgroup_dca_summary = _run_subgroup_dca_check(
            args, thresholds, failures, warnings, info,
        )

    # Summary
    summary = {
        "features_analyzed": features_analyzed,
        "n_features_analyzed": len(features_analyzed),
        "equalized_odds_gaps": all_equalized_odds_gaps,
        "max_equalized_odds_gap": (
            max(all_equalized_odds_gaps) if all_equalized_odds_gaps else None
        ),
        "disparate_impact_ratios": all_disparate_impact_ratios,
        "min_disparate_impact_ratio": (
            min(all_disparate_impact_ratios)
            if all_disparate_impact_ratios
            else None
        ),
        "fpr_gaps": all_fpr_gaps,
        "max_fpr_gap": max(all_fpr_gaps) if all_fpr_gaps else None,
        "fnr_gaps": all_fnr_gaps,
        "max_fnr_gap": max(all_fnr_gaps) if all_fnr_gaps else None,
        "ppv_gaps": all_ppv_gaps,
        "max_ppv_gap": max(all_ppv_gaps) if all_ppv_gaps else None,
        "calibration_slope_deviations": all_cal_slope_deviations,
        "max_calibration_slope_deviation": (
            max(all_cal_slope_deviations) if all_cal_slope_deviations else None
        ),
        "total_fairness_metrics_reported": total_fairness_metrics_reported,
        "subgroup_details": subgroup_details,
        "subgroup_dca": subgroup_dca_summary,
        "thresholds": thresholds,
    }

    return _finish(args, failures, warnings, info, thresholds, eval_report, summary)


def _run_subgroup_dca_check(
    args: argparse.Namespace,
    thresholds: Dict[str, float],
    failures: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    info: List[Dict[str, Any]],
) -> Optional[Dict[str, Any]]:
    """Compute subgroup-stratified DCA and flag any subgroup with net harm.

    Wraps `_gate_utils.subgroup_dca` (Vickers & Elkin 2006). A subgroup
    "fails" if its best net benefit across the clinically-relevant
    threshold band (default 0.05–0.20) is < 0 — i.e. the model would do
    net harm if its predictions drove treatment decisions for that group.
    """
    # Apply CLI threshold overrides
    pt_min = args.subgroup_dca_threshold_min
    pt_max = args.subgroup_dca_threshold_max
    if pt_min is not None:
        thresholds["subgroup_dca_threshold_min"] = pt_min
    if pt_max is not None:
        thresholds["subgroup_dca_threshold_max"] = pt_max
    nb_fail = thresholds["subgroup_dca_net_benefit_fail"]
    band_lo = thresholds["subgroup_dca_threshold_min"]
    band_hi = thresholds["subgroup_dca_threshold_max"]

    trace_path = args.prediction_trace
    group_col = args.subgroup_dca_column
    if not trace_path or not group_col:
        add_issue(
            warnings,
            "subgroup_dca_input_missing",
            "Subgroup-DCA was requested but --prediction-trace and/or "
            "--subgroup-dca-column was not supplied; subgroup DCA was "
            "skipped.",
            {
                "prediction_trace": trace_path,
                "subgroup_dca_column": group_col,
            },
        )
        return {"status": "skipped", "reason": "missing_input"}

    p = Path(trace_path).expanduser()
    if not p.is_file():
        add_issue(
            warnings,
            "subgroup_dca_input_unreadable",
            f"Prediction trace not found for subgroup-DCA: {p}",
            {"path": str(p)},
        )
        return {"status": "skipped", "reason": "trace_missing"}

    # Load with pandas if available; fall back to csv stdlib
    try:
        import pandas as pd  # type: ignore
        try:
            df = pd.read_csv(p)
        except Exception as exc:
            add_issue(
                warnings,
                "subgroup_dca_input_unreadable",
                f"Could not parse prediction trace CSV: {exc}",
                {"path": str(p), "error": str(exc)},
            )
            return {"status": "skipped", "reason": "trace_unreadable"}
        missing_cols = [c for c in ("y_true", "y_score", group_col) if c not in df.columns]
        if missing_cols:
            add_issue(
                warnings,
                "subgroup_dca_input_unreadable",
                "Prediction trace is missing required columns for subgroup-DCA.",
                {"missing_columns": missing_cols, "path": str(p)},
            )
            return {"status": "skipped", "reason": "missing_columns"}
        y_true = df["y_true"].tolist()
        y_score = df["y_score"].tolist()
        groups = df[group_col].astype(str).tolist()
    except ImportError:
        # Fallback: csv stdlib
        import csv as _csv
        try:
            with p.open("r", encoding="utf-8") as fh:
                rdr = _csv.DictReader(fh)
                rows = list(rdr)
        except Exception as exc:
            add_issue(
                warnings,
                "subgroup_dca_input_unreadable",
                f"Could not read prediction trace: {exc}",
                {"path": str(p), "error": str(exc)},
            )
            return {"status": "skipped", "reason": "trace_unreadable"}
        if not rows:
            add_issue(
                warnings,
                "subgroup_dca_skipped_insufficient_data",
                "Prediction trace is empty.",
                {"path": str(p)},
            )
            return {"status": "skipped", "reason": "empty_trace"}
        sample = rows[0]
        missing_cols = [c for c in ("y_true", "y_score", group_col) if c not in sample]
        if missing_cols:
            add_issue(
                warnings,
                "subgroup_dca_input_unreadable",
                "Prediction trace is missing required columns for subgroup-DCA.",
                {"missing_columns": missing_cols, "path": str(p)},
            )
            return {"status": "skipped", "reason": "missing_columns"}
        y_true, y_score, groups = [], [], []
        for r in rows:
            try:
                y_true.append(float(r["y_true"]))
                y_score.append(float(r["y_score"]))
                groups.append(str(r[group_col]))
            except (TypeError, ValueError):
                continue

    # Build threshold grid restricted to the clinically-relevant band so the
    # downstream "best NB on band" check is well-defined.
    try:
        n_steps = max(2, int(round((band_hi - band_lo) / 0.02)) + 1)
        step = (band_hi - band_lo) / max(n_steps - 1, 1)
        band_thresholds = [round(band_lo + step * i, 4) for i in range(n_steps)]
    except (TypeError, ValueError, ZeroDivisionError):
        band_thresholds = None

    # Lazy import to avoid pulling numpy at module-load time
    from _gate_utils import subgroup_dca as _subgroup_dca

    try:
        dca_result = _subgroup_dca(
            y_true=y_true,
            y_score=y_score,
            group_labels=groups,
            thresholds=band_thresholds,
        )
    except Exception as exc:
        add_issue(
            warnings,
            "subgroup_dca_skipped_insufficient_data",
            f"Subgroup-DCA computation failed: {exc}",
            {"error": str(exc)},
        )
        return {"status": "error", "reason": str(exc)}

    # Walk each group's curve and flag any with best NB on band < fail.
    group_optimal = dca_result.get("group_optimal_net_benefit", {}) or {}
    if not group_optimal:
        add_issue(
            warnings,
            "subgroup_dca_skipped_insufficient_data",
            "Subgroup-DCA returned no per-group curves (likely all subgroups "
            "below the n>=20 minimum).",
            {"groups_seen": dca_result.get("groups", [])},
        )
        return {
            "status": "insufficient_data",
            "groups": dca_result.get("groups", []),
            "n_thresholds": dca_result.get("n_thresholds"),
        }

    failing_groups: List[Dict[str, Any]] = []
    for grp_label, best_nb in group_optimal.items():
        nb = _to_float(best_nb)
        if nb is None:
            continue
        if nb < nb_fail:
            failing_groups.append({
                "group": grp_label,
                "best_net_benefit": nb,
                "threshold_band": [band_lo, band_hi],
            })

    if failing_groups:
        add_issue(
            failures,
            "fairness_subgroup_dca_negative",
            f"{len(failing_groups)} subgroup(s) have net benefit < "
            f"{nb_fail:.2f} across the {band_lo:.2f}–{band_hi:.2f} threshold "
            "band — the model would do net harm in that subgroup if used to "
            "drive treatment decisions. "
            f"Groups: {[g['group'] for g in failing_groups]}.",
            {
                "failing_subgroups": failing_groups,
                "threshold_band": [band_lo, band_hi],
                "net_benefit_fail_threshold": nb_fail,
                "subgroup_column": group_col,
                "equity_gap": dca_result.get("equity_gap"),
                "worst_group": dca_result.get("worst_group"),
            },
        )

    return {
        "status": "computed",
        "subgroup_column": group_col,
        "threshold_band": [band_lo, band_hi],
        "net_benefit_fail_threshold": nb_fail,
        "group_optimal_net_benefit": group_optimal,
        "equity_gap": dca_result.get("equity_gap"),
        "best_group": dca_result.get("best_group"),
        "worst_group": dca_result.get("worst_group"),
        "n_thresholds": dca_result.get("n_thresholds"),
        "failing_subgroups": failing_groups,
    }


def _finish(
    args: argparse.Namespace,
    failures: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    info: List[Dict[str, Any]],
    thresholds: Dict[str, float],
    eval_report: Optional[Dict[str, Any]],
    summary: Optional[Dict[str, Any]] = None,
) -> int:
    from _gate_utils import write_json as _write_report

    should_fail = bool(failures) or (args.strict and bool(warnings))
    status = "fail" if should_fail else "pass"

    fi = [GateIssue.from_legacy(f, Severity.ERROR) for f in failures]
    wi = [GateIssue.from_legacy(w, Severity.WARNING) for w in warnings]
    for issue in fi + wi:
        if not issue.remediation:
            issue.remediation = get_remediation(issue.code)

    combined_summary = dict(summary or {})
    combined_summary["thresholds"] = thresholds
    combined_summary["info"] = info

    report = build_report_envelope(
        gate_name="fairness_equity_gate",
        status=status,
        strict_mode=bool(args.strict),
        failures=fi,
        warnings=wi,
        summary=combined_summary,
        input_files={
            "evaluation_report": str(Path(args.evaluation_report).expanduser().resolve()),
        },
    )

    if args.report:
        _write_report(Path(args.report).expanduser().resolve(), report)

    print_gate_summary("fairness_equity_gate", status, fi, wi, bool(args.strict), get_gate_elapsed())
    return 2 if should_fail else 0


if __name__ == "__main__":
    from _gate_utils import start_gate_timer
    start_gate_timer()
    raise SystemExit(main())
